[package]
name = "willow-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
genawaiter = "0.99.1"
hex = "0.4.3"
postcard = { version = "1.0.8", features = ["use-std"] }
redb = "2.0.0"
self_cell = "1.0.3"
serde = { version = "1.0.198", features = ["derive"] }
